import { ProjectFile } from "./project-file";

export function getSrcFiles(): ProjectFile[] {
    return [
        srcAppTs(),
        srcConfigEnvTs(),
        srcConfigLoggerTs(),
        srcConfigStartupBannerTs(),
        srcControllersHealthControllerTs(),
        srcEntitiesUserEntityTs(),
        srcRepositoriesUserRepositoryInterfaceTs(),
        srcRepositoriesUserRepositoryTs(),
        srcServicesUserServiceInterfaceTs(),
        srcServicesUserServiceTs(),
        srcDtoCreateUserDtoTs(),
        srcDtoUserResponseDtoTs(),
        srcDatabaseMigrateTs(),
        srcDatabaseSyncSchemaTs(),
        srcDatabaseGenerateMigrationTs(),
        srcDatabaseEntityScanTs(),
        srcDatabaseMigrationsDirKeep(),
        srcAdviceGlobalExceptionFilterTs(),
        srcServicesUserCreatedListenerTs(),
    ];
}

function srcAppTs(): ProjectFile {
    return {
        path: "src/app.ts",
        content: [
            'import "@solumjs/core";',
            'import { createApplication, createEnvConfig, loadEnv } from "@solumjs/config";',
            'import { env } from "@config/env";',
            'import { logger } from "@config/logger";',
            'import { printStartupBanner } from "@config/startup-banner";',
            "",
            "loadEnv();",
            "",
            "createApplication({",
            "    logger,",
            "    config: createEnvConfig(env),",
            "    scanBaseDir: __dirname,",
            '    scanDirs: [',
            '        "config/beans",',
            '        "repositories",',
            '        "services",',
            '        "controllers",',
            '        "advice",',
            '        "auth",',
            '        "tasks",',
            '    ],',
            "    bodyLimitBytes: 10 * 1024,",
            "    onListen: printStartupBanner,",
            "});",
        ].join("\n"),
    };
}

function srcConfigEnvTs(): ProjectFile {
    return {
        path: "src/config/env.ts",
        content: [
            'import { loadEnv } from "@solumjs/config";',
            "",
            "loadEnv();",
            "",
            "type EnvValue = string | number;",
            "",
            "interface FieldSpec {",
            "    required?: boolean;",
            "    default?: EnvValue | ((env: Record<string, EnvValue>) => EnvValue);",
            "    choices?: string[];",
            "    isPort?: boolean;",
            "    isNumber?: boolean;",
            "    requiredWhen?: (env: Record<string, EnvValue>) => boolean;",
            "}",
            "",
            'const DB_CLIENTS = ["postgres", "mysql", "mssql", "oracle", "sqlite"];',
            "",
            "const DEFAULT_PORTS: Record<string, number> = {",
            "    postgres: 5432,",
            "    mysql: 3306,",
            "    mssql: 1433,",
            "    oracle: 1521,",
            "    sqlite: 0,",
            "};",
            "",
            "const SCHEMA: Record<string, FieldSpec> = {",
            '    NODE_ENV: { required: true, choices: ["development", "production", "test"] },',
            "    PORT: { default: 3000, isPort: true },",
            "    JWT_SECRET: { required: true },",
            "    RATE_LIMIT_MAX: { default: 100, isNumber: true },",
            '    DB_CLIENT: { default: "postgres", choices: DB_CLIENTS },',
            '    DB_FILE: { default: "./data/app.db" },',
            '    DB_HOST: { default: "localhost", requiredWhen: (e) => e.DB_CLIENT !== "sqlite" },',
            "    DB_PORT: { default: (e) => DEFAULT_PORTS[e.DB_CLIENT as string] ?? 5432, isPort: true },",
            '    DB_NAME: { requiredWhen: (e) => e.DB_CLIENT !== "sqlite" },',
            '    DB_USER: { requiredWhen: (e) => e.DB_CLIENT !== "sqlite" },',
            '    DB_PASSWORD: { requiredWhen: (e) => e.DB_CLIENT !== "sqlite" },',
            "    MONGO_URL: {},",
            "    REDIS_URL: {},",
            "    CORS_ORIGIN: {},",
            "};",
            "",
            "function validate(spec: FieldSpec, key: string, raw: string | undefined, current: Record<string, EnvValue>): EnvValue {",
            '    if (raw === undefined || raw === "") {',
            '        if (typeof spec.default === "function") return spec.default(current);',
            "        if (spec.default !== undefined) return spec.default;",
            "        if (spec.required || spec.requiredWhen?.(current)) {",
            '            throw new Error(`Missing required environment variable "${key}"`);',
            "        }",
            '        return "";',
            "    }",
            "",
            "    if (spec.choices && !spec.choices.includes(raw)) {",
            '        throw new Error(`Environment variable "${key}" must be one of: ${spec.choices.join(", ")}`);',
            "    }",
            "",
            "    if (spec.isPort) {",
            "        const port = Number(raw);",
            "        if (!Number.isInteger(port) || port < 0 || port > 65535) {",
            '            throw new Error(`Environment variable "${key}" must be a valid port number`);',
            "        }",
            "        return port;",
            "    }",
            "",
            "    if (spec.isNumber) {",
            "        const num = Number(raw);",
            "        if (!Number.isFinite(num)) {",
            '            throw new Error(`Environment variable "${key}" must be a number`);',
            "        }",
            "        return num;",
            "    }",
            "",
            "    return raw;",
            "}",
            "",
            "function buildEnv(): Record<string, EnvValue> {",
            "    const errors: string[] = [];",
            "    const result: Record<string, EnvValue> = {};",
            "",
            "    for (const [key, spec] of Object.entries(SCHEMA)) {",
            "        try {",
            "            result[key] = validate(spec, key, process.env[key], result);",
            "        } catch (err) {",
            "            errors.push((err as Error).message);",
            "        }",
            "    }",
            "",
            "    if (errors.length > 0) {",
            '        throw new Error(`Invalid environment configuration:\\n${errors.map((e) => ` - ${e}`).join("\\n")}`);',
            "    }",
            "",
            "    return result;",
            "}",
            "",
            "export const env = buildEnv();",
        ].join("\n"),
    };
}

function srcConfigLoggerTs(): ProjectFile {
    return {
        path: "src/config/logger.ts",
        content: [
            'import { styleText } from "util";',
            'import { env } from "./env";',
            "",
            'type Level = "debug" | "info" | "warn" | "error";',
            "",
            "const LEVEL_WEIGHT: Record<Level, number> = { debug: 10, info: 20, warn: 30, error: 40 };",
            "",
            'const LEVEL_COLOR: Record<Level, "blue" | "green" | "yellow" | "red"> = {',
            '    debug: "blue",',
            '    info: "green",',
            '    warn: "yellow",',
            '    error: "red",',
            "};",
            "",
            "interface Sink {",
            "    write(level: Level, message: string, payload: Record<string, unknown>): void;",
            "}",
            "",
            'const PRETTY_SKIP_KEYS = new Set(["time", "level", "msg", "env", "pid"]);',
            "",
            "function formatValue(value: unknown): string {",
            '    if (typeof value === "string") return value;',
            "    if (value instanceof Error) return value.message;",
            "    try { return JSON.stringify(value) ?? String(value); } catch { return String(value); }",
            "}",
            "",
            "function formatPretty(level: Level, message: string, payload: Record<string, unknown>): string {",
            "    const time = new Date();",
            '    const hh = String(time.getHours()).padStart(2, "0");',
            '    const mm = String(time.getMinutes()).padStart(2, "0");',
            '    const ss = String(time.getSeconds()).padStart(2, "0");',
            "    const stamp = `${time.toISOString().slice(0, 10)} ${hh}:${mm}:${ss}`;",
            "    const coloredLevel = styleText(LEVEL_COLOR[level], level.toUpperCase());",
            "    let line = `[${stamp}] ${coloredLevel}:`;",
            "    if (message) line += ` ${styleText(\"cyan\", message)}`;",
            "    const extras: string[] = [];",
            "    for (const [key, value] of Object.entries(payload)) {",
            "        if (PRETTY_SKIP_KEYS.has(key)) continue;",
            '        if (key === "err" && value instanceof Error) {',
            '            extras.push(styleText("red", `${value.name}: ${value.message}`));',
            "            continue;",
            "        }",
            '        extras.push(`${styleText("magenta", key)}=${formatValue(value)}`);',
            "    }",
            "    if (extras.length > 0) line += ` ${styleText(\"dim\", `{${extras.join(\", \")}}`)}`;",
            "    return line;",
            "}",
            "",
            "class Logger {",
            "    constructor(private readonly minWeight: number, private readonly bindings: Record<string, unknown>, private readonly sinks: Sink[]) {}",
            "    child(bindings: Record<string, unknown>): Logger { return new Logger(this.minWeight, { ...this.bindings, ...bindings }, this.sinks); }",
            "    debug(arg: object | string, message?: string): void { this.write(\"debug\", arg, message); }",
            "    info(arg: object | string, message?: string): void { this.write(\"info\", arg, message); }",
            "    warn(arg: object | string, message?: string): void { this.write(\"warn\", arg, message); }",
            "    error(arg: object | string, message?: string): void { this.write(\"error\", arg, message); }",
            "    private write(level: Level, arg: object | string, message?: string): void {",
            "        if (LEVEL_WEIGHT[level] < this.minWeight) return;",
            '        const extra = typeof arg === "object" && arg !== null ? (arg as Record<string, unknown>) : {};',
            '        const text = message ?? (typeof arg === "string" ? arg : "");',
            "        const payload = { ...extra, ...this.bindings };",
            "        for (const sink of this.sinks) sink.write(level, text, payload);",
            "    }",
            "}",
            "",
            'const isProduction = env.NODE_ENV === "production";',
            "const minWeight = isProduction ? LEVEL_WEIGHT.info : LEVEL_WEIGHT.debug;",
            "const baseBindings = { env: env.NODE_ENV, pid: process.pid };",
            "",
            "export const logger = new Logger(minWeight, baseBindings, [{",
            "    write(level, message, payload) { console.log(formatPretty(level, message, payload)); },",
            "}]);",
        ].join("\n"),
    };
}

function srcConfigStartupBannerTs(): ProjectFile {
    return {
        path: "src/config/startup-banner.ts",
        content: [
            'import { styleText } from "util";',
            'import { env } from "./env";',
            "",
            "export function printStartupBanner(port: number): void {",
            "    const banner = `",
            "${styleText(\"cyan\", \"===\")} Server started successfully",
            "  Environment : ${env.NODE_ENV}",
            "  Port        : ${port}",
            "  URL         : http://localhost:${port}",
            "  Health      : http://localhost:${port}/health",
            "  PID         : ${process.pid}",
            "  Node        : ${process.version}",
            "${styleText(\"cyan\", \"===\")}`;",
            "    console.log(banner);",
            "}",
        ].join("\n"),
    };
}

function srcControllersHealthControllerTs(): ProjectFile {
    return {
        path: "src/controllers/health.controller.ts",
        content: [
            'import { RestController, Get } from "@solumjs/http";',
            "",
            '@RestController("")',
            "export class HealthController {",
            '    @Get("/health")',
            "    async health() {",
            "        return {",
            '            status: "UP",',
            '            timestamp: new Date().toISOString(),',
            "            uptime: process.uptime(),",
            "        };",
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcEntitiesUserEntityTs(): ProjectFile {
    return {
        path: "src/entities/user.entity.ts",
        content: [
            'import { Column, ColumnType, CreatedAtColumn, Entity, PrimaryGeneratedColumn } from "@solumjs/orm";',
            "",
            '@Entity("users")',
            "export class User {",
            "    @PrimaryGeneratedColumn(ColumnType.UUID)",
            "    public readonly id!: string;",
            "",
            "    @Column({ type: ColumnType.VARCHAR, length: 255 })",
            "    public name!: string;",
            "",
            "    @Column({ type: ColumnType.VARCHAR, length: 255, unique: true })",
            "    public email!: string;",
            "",
            "    @Column({ type: ColumnType.VARCHAR, length: 255, nullable: true })",
            "    public passwordHash?: string;",
            "",
            '    @Column({ type: ColumnType.VARCHAR, length: 32, default: "\'USER\'" })',
            "    public role!: string;",
            "",
            "    @CreatedAtColumn()",
            "    public readonly createdAt!: Date;",
            "",
            "    constructor(id: string, name: string, email: string, createdAt: Date = new Date(), role: string = \"USER\") {",
            "        this.id = id;",
            "        this.name = name;",
            "        this.email = email;",
            "        this.role = role;",
            "        this.createdAt = createdAt;",
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcRepositoriesUserRepositoryInterfaceTs(): ProjectFile {
    return {
        path: "src/repositories/user.repository.interface.ts",
        content: [
            'import { User } from "@entities/user.entity";',
            'import { IBaseRepository } from "@solumjs/database";',
            "",
            "export interface IUserRepository extends IBaseRepository<User, string> {",
            "    findByEmail(email: string): Promise<User | null>;",
            "}",
        ].join("\n"),
    };
}

function srcRepositoriesUserRepositoryTs(): ProjectFile {
    return {
        path: "src/repositories/user.repository.ts",
        content: [
            'import { Bean } from "@solumjs/core";',
            'import { BaseRepository } from "@solumjs/database";',
            'import { IUserRepository } from "./user.repository.interface";',
            'import { User } from "@entities/user.entity";',
            "",
            '@Bean("IUserRepository")',
            "export class UserRepository extends BaseRepository<User, string> implements IUserRepository {",
            "    protected readonly entityCtor = User;",
            "",
            "    async findByEmail(email: string): Promise<User | null> {",
            '        return this.query().where("email", email).first();',
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcServicesUserServiceInterfaceTs(): ProjectFile {
    return {
        path: "src/services/user.service.interface.ts",
        content: [
            'import { CreateUserDto } from "@dto/create-user.dto";',
            'import { User } from "@entities/user.entity";',
            "",
            "export interface IUserService {",
            "    createUser(dto: CreateUserDto): Promise<User>;",
            "    getUserById(id: string): Promise<User>;",
            "}",
        ].join("\n"),
    };
}

function srcServicesUserServiceTs(): ProjectFile {
    return {
        path: "src/services/user.service.ts",
        content: [
            'import { IUserRepository } from "@repositories/user.repository.interface";',
            'import { IUserService } from "./user.service.interface";',
            'import { CreateUserDto } from "@dto/create-user.dto";',
            'import { User } from "@entities/user.entity";',
            'import { ConflictException, NotFoundException } from "@solumjs/core";',
            'import { inject } from "@solumjs/core";',
            'import { randomUUID } from "crypto";',
            'import { Bean } from "@solumjs/core";',
            'import { hashPassword } from "@solumjs/auth";',
            'import { logger } from "@config/logger";',
            "",
            '@Bean("IUserService")',
            "export class UserService implements IUserService {",
            "    constructor(",
            '        @inject("IUserRepository")',
            "        private readonly userRepository: IUserRepository,",
            "    ) {}",
            "",
            "    async createUser(dto: CreateUserDto): Promise<User> {",
            "        const id = randomUUID();",
            "        const existing = await this.userRepository.findByEmail(dto.email);",
            "        if (existing) {",
            '            throw new ConflictException(`Email ${dto.email} is already registered`);',
            "        }",
            "",
            "        const user = new User(id, dto.name, dto.email);",
            "        if (dto.password) {",
            "            user.passwordHash = hashPassword(dto.password);",
            "        }",
            "",
            "        return this.userRepository.save(user);",
            "    }",
            "",
            "    async getUserById(id: string): Promise<User> {",
            "        const user = await this.userRepository.findById(id);",
            "        if (!user) {",
            '            throw new NotFoundException(`User with id ${id} not found`);',
            "        }",
            "        return user;",
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcServicesUserCreatedListenerTs(): ProjectFile {
    return {
        path: "src/services/user-created.listener.ts",
        content: [
            'import { OnEvent } from "@solumjs/events";',
            'import { logger } from "@config/logger";',
            "",
            "export class UserCreatedListener {",
            '    @OnEvent("USER_CREATED")',
            "    handleUserCreated(payload: { userId: string; email: string }) {",
            '        logger.info({ userId: payload.userId }, "User created event received");',
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcDtoCreateUserDtoTs(): ProjectFile {
    return {
        path: "src/dto/create-user.dto.ts",
        content: [
            "export interface CreateUserDto {",
            "    name: string;",
            "    email: string;",
            "    password?: string;",
            "}",
        ].join("\n"),
    };
}

function srcDtoUserResponseDtoTs(): ProjectFile {
    return {
        path: "src/dto/user-response.dto.ts",
        content: [
            'import { User } from "@entities/user.entity";',
            "",
            "export class UserResponseDto {",
            "    id!: string;",
            "    name!: string;",
            "    email!: string;",
            "    role!: string;",
            "    createdAt!: Date;",
            "",
            "    static fromEntity(user: User): UserResponseDto {",
            "        const dto = new UserResponseDto();",
            "        dto.id = user.id;",
            "        dto.name = user.name;",
            "        dto.email = user.email;",
            "        dto.role = user.role;",
            "        dto.createdAt = user.createdAt;",
            "        return dto;",
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcAdviceGlobalExceptionFilterTs(): ProjectFile {
    return {
        path: "src/advice/global-exception-filter.ts",
        content: [
            'import { ExceptionHandler } from "@solumjs/middlewares";',
            'import { SolumjsRequest } from "@solumjs/http";',
            'import { NotFoundException, BadRequestException } from "@solumjs/core";',
            "",
            "export class GlobalExceptionFilter {",
            "    @ExceptionHandler(NotFoundException)",
            "    handleNotFound(err: NotFoundException, req: SolumjsRequest) {",
            "        req.log.warn({ path: req.path }, err.message);",
            '        return { status: "error", code: "NOT_FOUND", message: err.message };',
            "    }",
            "",
            "    @ExceptionHandler(BadRequestException)",
            "    handleBadRequest(err: BadRequestException, req: SolumjsRequest) {",
            "        req.log.warn({ path: req.path }, err.message);",
            '        return { status: "error", code: "BAD_REQUEST", message: err.message };',
            "    }",
            "",
            "    @ExceptionHandler(Error)",
            "    handleGeneric(err: Error, req: SolumjsRequest) {",
            "        req.log.error({ path: req.path, err }, \"Unhandled error\");",
            '        return { status: "error", code: "INTERNAL_ERROR", message: "Internal server error" };',
            "    }",
            "}",
        ].join("\n"),
    };
}

function srcDatabaseMigrateTs(): ProjectFile {
    return {
        path: "src/database/migrate.ts",
        content: [
            'import path from "path";',
            'import { loadEnv } from "@solumjs/config";',
            'import { MigrationRunner, createDatabaseDriver } from "@solumjs/database";',
            "",
            "loadEnv();",
            "",
            "async function main() {",
            '    const command = process.argv[2] ?? "up";',
            "",
            "    const driver = await createDatabaseDriver();",
            '    const migrationsDir = path.join(__dirname, "migrations");',
            "    const runner = new MigrationRunner(driver, migrationsDir);",
            "",
            "    try {",
            "        switch (command) {",
            '            case "up":',
            "                await runner.run();",
            "                break;",
            '            case "down": {',
            "                const steps = Number(process.argv[3]) || 1;",
            "                await runner.rollback(steps);",
            "                break;",
            "            }",
            '            case "status":',
            "                await runner.status();",
            "                break;",
            "            default:",
            '                console.error(`Unknown command: "${command}". Use "up", "down [steps]", or "status"`);',
            "                process.exit(1);",
            "        }",
            "    } catch (err) {",
            '        console.error("Migration failed:", err);',
            "        process.exit(1);",
            "    } finally {",
            "        await driver.close();",
            "    }",
            "}",
            "",
            "main();",
        ].join("\n"),
    };
}

function srcDatabaseSyncSchemaTs(): ProjectFile {
    return {
        path: "src/database/sync-schema.ts",
        content: [
            'import { loadEnv } from "@solumjs/config";',
            'import { SchemaSync } from "@solumjs/orm";',
            'import { entityScan } from "./entity-scan";',
            "",
            "loadEnv();",
            "",
            "async function main() {",
            '    const command = process.argv[2] ?? "validate";',
            "    const driver = await import(\"@solumjs/database\").then((m) => m.createDatabaseDriver());",
            "    const sync = new SchemaSync(driver, entityScan);",
            "",
            "    try {",
            '        if (command === "update") {',
            "            await sync.update();",
            '            console.log("Schema updated successfully");',
            '        } else if (command === "validate") {',
            "            const result = await sync.validate();",
            "            if (result.ok) {",
            '                console.log("Schema is in sync");',
            "            } else {",
            "                console.error(\"Schema drift detected:\");",
            "                for (const diff of result.diffs) console.error(`  - ${diff}`);",
            "                process.exit(1);",
            "            }",
            "        } else {",
            '            console.error(`Unknown command: "${command}". Use "validate" or "update"`);',
            "            process.exit(1);",
            "        }",
            "    } finally {",
            "        await driver.close();",
            "    }",
            "}",
            "",
            "main();",
        ].join("\n"),
    };
}

function srcDatabaseGenerateMigrationTs(): ProjectFile {
    return {
        path: "src/database/generate-migration.ts",
        content: [
            'import fs from "fs";',
            'import path from "path";',
            'import { loadEnv } from "@solumjs/config";',
            "",
            "loadEnv();",
            "",
            "function toSnakeCase(str: string): string {",
            "    return str.replace(/([A-Z])/g, \"_$1\").toLowerCase().replace(/^_/, \"\");",
            "}",
            "",
            "function main() {",
            "    const name = process.argv[2];",
            "    if (!name) {",
            '        console.error("Usage: migrate:generate <MigrationName>");',
            "        process.exit(1);",
            "    }",
            "",
            '    const migrationsDir = path.join(__dirname, "migrations");',
            "    fs.mkdirSync(migrationsDir, { recursive: true });",
            "",
            "    const timestamp = new Date().toISOString().replace(/[:.]/g, \"-\").slice(0, 19);",
            "    const fileName = `${timestamp}-${toSnakeCase(name)}.ts`;",
            "    const filePath = path.join(migrationsDir, fileName);",
            "",
            "    const content = [",
            "        \"export async function up(driver: any): Promise<void> {\",",
            "            \"// TODO: Add migration SQL\",",
            "        \"}\",",
            "        \"\",",
            "        \"export async function down(driver: any): Promise<void> {\",",
            "            \"// TODO: Add rollback SQL\",",
            "        \"}\",",
            "    ].join(\"\\n\");",
            "",
            "    fs.writeFileSync(filePath, content, \"utf8\");",
            "    console.log(`Created migration: ${filePath}`);",
            "}",
            "",
            "main();",
        ].join("\n"),
    };
}

function srcDatabaseEntityScanTs(): ProjectFile {
    return {
        path: "src/database/entity-scan.ts",
        content: [
            'import { User } from "@entities/user.entity";',
            "",
            "export const entityScan = [User];",
        ].join("\n"),
    };
}

function srcDatabaseMigrationsDirKeep(): ProjectFile {
    return {
        path: "src/database/migrations/.gitkeep",
        content: "",
    };
}
