import { ProjectFile } from "./project-file";

export function getRootFiles(pkg: string): ProjectFile[] {
    return [
        {
            path: "package.json",
            content: JSON.stringify({
                name: pkg,
                version: "0.1.0",
                private: true,
                scripts: {
                    dev: "ts-node-dev --respawn --transpile-only -r tsconfig-paths/register src/app.ts",
                    build: "tsc",
                    start: "node -r ./prod-paths.js dist/app.js",
                    test: "jest",
                    migrate: "ts-node -r tsconfig-paths/register src/database/migrate.ts up",
                    "migrate:status": "ts-node -r tsconfig-paths/register src/database/migrate.ts status",
                    "migrate:generate": "ts-node -r tsconfig-paths/register src/database/generate-migration.ts",
                    "migrate:down": "ts-node -r tsconfig-paths/register src/database/migrate.ts down",
                    "schema:sync": "ts-node -r tsconfig-paths/register src/database/sync-schema.ts validate",
                    "schema:sync:update": "ts-node -r tsconfig-paths/register src/database/sync-schema.ts update",
                },
                dependencies: {
                    "@solumjs/auth": "^0.2.0",
                    "@solumjs/cache": "^0.2.0",
                    "@solumjs/config": "^0.2.0",
                    "@solumjs/core": "^0.2.0",
                    "@solumjs/database": "^0.2.0",
                    "@solumjs/events": "^0.2.0",
                    "@solumjs/http": "^0.2.0",
                    "@solumjs/middlewares": "^0.2.0",
                    "@solumjs/orm": "^0.2.0",
                    "@solumjs/schedule": "^0.2.0",
                    "@solumjs/validation": "^0.2.0",
                    "@solumjs/aop": "^0.2.0",
                    pg: "^8.23.0",
                },
                devDependencies: {
                    "@types/jest": "^30.0.0",
                    "@types/node": "^26.2.0",
                    "@types/pg": "^8.23.1",
                    jest: "^30.4.2",
                    "ts-jest": "^29.4.12",
                    "ts-node-dev": "^2.0.0",
                    "tsconfig-paths": "^4.2.0",
                    typescript: "^6.0.3",
                },
            }, null, 2),
        },
        {
            path: "tsconfig.json",
            content: JSON.stringify({
                compilerOptions: {
                    target: "ES2022",
                    module: "NodeNext",
                    moduleResolution: "NodeNext",
                    outDir: "dist",
                    rootDir: "./src",
                    declaration: true,
                    strict: true,
                    esModuleInterop: true,
                    skipLibCheck: true,
                    forceConsistentCasingInFileNames: true,
                    resolveJsonModule: true,
                    experimentalDecorators: true,
                    emitDecoratorMetadata: true,
                    paths: {
                        "@config/*": ["./src/config/*"],
                        "@controllers/*": ["./src/controllers/*"],
                        "@database/*": ["./src/database/*"],
                        "@dto/*": ["./src/dto/*"],
                        "@entities/*": ["./src/entities/*"],
                        "@repositories/*": ["./src/repositories/*"],
                        "@services/*": ["./src/services/*"],
                        "@advice/*": ["./src/advice/*"],
                    },
                    types: ["node", "jest"],
                },
                include: ["src"],
            }, null, 2),
        },
        {
            path: "prod-paths.js",
            content: [
                'const { register } = require("tsconfig-paths");',
                "",
                "register({",
                '    baseUrl: require("path").join(__dirname, "dist"),',
                "    paths: {",
                '        "@config/*": ["config/*"],',
                '        "@controllers/*": ["controllers/*"],',
                '        "@database/*": ["database/*"],',
                '        "@dto/*": ["dto/*"],',
                '        "@entities/*": ["entities/*"],',
                '        "@repositories/*": ["repositories/*"],',
                '        "@services/*": ["services/*"],',
                '        "@advice/*": ["advice/*"]',
                "    }",
                "});",
            ].join("\n"),
        },
        {
            path: "jest.config.js",
            content: [
                'const tsconfig = require("./tsconfig.json");',
                "",
                "function buildModuleNameMapper() {",
                "    const paths = tsconfig.compilerOptions.paths || {};",
                "    const mapper = {};",
                "    for (const [alias, targets] of Object.entries(paths)) {",
                "        const pattern = `^${alias.replace(/\\*/g, '(.*)')}$`;",
                "        mapper[pattern] = targets.map((target) =>",
                "            `<rootDir>/${target.replace(/^\\.\\//, '').replace(/\\*/g, '$1')}`",
                "        );",
                "    }",
                "    return mapper;",
                "}",
                "",
                "module.exports = {",
                '    preset: "ts-jest",',
                '    testEnvironment: "node",',
                '    testMatch: ["**/__test__/**/*.test.ts", "**/__tests__/**/*.test.ts"],',
                "    transform: {",
                '        "^.+\\.ts$": ["ts-jest", {}],',
                "    },",
                '    moduleFileExtensions: ["ts", "js", "json"],',
                "    moduleNameMapper: buildModuleNameMapper(),",
                "};",
            ].join("\n"),
        },
        {
            path: ".env.example",
            content: [
                "# ===== Application =====",
                "NODE_ENV=development",
                "PORT=3000",
                "",
                "# ===== Security =====",
                "JWT_SECRET=your-secret-key-here",
                "RATE_LIMIT_MAX=100",
                "CORS_ORIGIN=http://localhost:3000",
                "",
                "# ===== Database =====",
                "DB_CLIENT=postgres",
                "DB_HOST=localhost",
                "DB_PORT=5432",
                `DB_NAME=${pkg}`,
                "DB_USER=postgres",
                "DB_PASSWORD=change-me",
                "",
                "# ===== MongoDB (optional) =====",
                "# MONGO_URL=mongodb://localhost:27017/myapp",
                "",
                "# ===== Redis (optional) =====",
                "# REDIS_URL=redis://localhost:6379",
            ].join("\n"),
        },
        {
            path: ".gitignore",
            content: ["node_modules/", "dist/", "logs/", ".env", "*.log", "data/"].join("\n"),
        },
    ];
}
